### ISSUE TITLE
SQL Query Exception after publishing package

### ISSUE THREAD

**Issue by lennow** [hackerESQ/laravel-google-calendar#1]
Hi, I followed the instructions with a fresh Laravel 5.7 installation, but the following error occured after migration:

![gclaravel](https://user-images.githubusercontent.com/22936131/47094305-45b95280-d22b-11e8-867b-3704a2977429.png)

I'd appreciate any solution - thanks a lot!

**Comment by hackerESQ** [comment]
What version of MariaDB are you using? It appears older versions do not
support the JSON field type.

https://mariadb.com/resources/blog/json-mariadb-102

If you cannot update your MariaDB installation, try changing the
'update_users_table.php' in your migrations folder to use 'longtext' for
the 'google_access_token.'

Let me know if either of these options solves your issue!

**Comment by lennow** [comment]
The second option seemed to solve the issue - after changing 'json' to 'longtext' for the google_access_token, the migration finally worked. Thanks a lot! :)

**Comment by hackerESQ** [comment]
Great! I will close this issue. By the way, what version of MariaDB are you using?

**Comment by lennow** [comment]
I'm using XAMPP for Windows with phpmyadmin, the MariaDB is version 10.1.36.

**Comment by hackerESQ** [comment]
Okay, yeah, that makes me feel a bit better. This would migrate natively in MariaDB 10.2 +. But this workaround works for any DB that does not support 'json' types. I've updated the readme.
