### ISSUE TITLE
Get free time slot between given date time

### ISSUE THREAD

**Issue by stacybot123** [hackerESQ/laravel-google-calendar#4]
Hi,

How can I get free time slots in a given date and time?

Thanks

**Comment by hackerESQ** [comment]
Hi can you explain what you're looking to do? This package is a wrapper for google calendar API, which does not have "slot" capabilities. Though, you can probably build that into this package as a feature. I'd be willing to review a PR if you put one together.

**Comment by stacybot123** [comment]
Hi,

Sorry for the delay , I was trying to use google FreeBusy query.  I added below code in the GoogleCalendar.php 

```
public function FreeBusyTime($start = NULL, $end = NULL, $timezone = NULL) {

        // Set defaults
       
        $start = empty($start) ? Carbon::now()->startOfMonth() : $start;
        $end = empty($end) ? Carbon::now()->endOfMonth() : $end;
        
        $this->client->setAccessToken($this->accessToken);
        $service = new Google_Service_Calendar($this->client);
        $freebusy_req = new Google_Service_Calendar_FreeBusyRequest();
        $freebusy_req->setTimeMin(Carbon::parse($start, $timezone)->toIso8601String());
        $freebusy_req->setTimeMax(Carbon::parse($end, $timezone)->toIso8601String());
        $freebusy_req->setTimeZone($timezone);
        $item = new Google_Service_Calendar_FreeBusyRequestItem();
        $item->setId('primary');
        $freebusy_req->setItems(array($item));
        $query = json_decode(json_encode($service->freebusy->query($freebusy_req)), true);

        
            $fullcalendar = [];
            foreach ($query['calendars']['primary']['busy'] as $event) {
                $fullcalendar[] = array(
                    'start' => Carbon::parse($event['start'],$timezone)->toDateTimeString(),
                    'end' => Carbon::parse($event['end'],$timezone)->toDateTimeString(),
                    );
                
            }
            
            return $fullcalendar;
        }
```

I ended up finding that its almost same as listing same thing as it returns in "listEvents" function. I thought that FreeBusy will give me the free time slots on calendar.

Then I wrote a function which will return free time in an interval of 30 minutes , and exclude those that are already booked. For example: I have an appointment between 3:00PM - 4PM , so 3:00 PM is not in the list in the image attached

![appointment](https://user-images.githubusercontent.com/26300235/57586740-ca492680-7517-11e9-8be6-e51d503a8aee.png)
